name: Charmed kubeflow + mlflow bundle
base:
  kernel_image: quay.io/testfaster/ignite-kernel
  os_dockerfile: |-
    # This dockerfile defines the base disk image for your VMs
    FROM quay.io/testfaster/kube-ubuntu
    ENV cache-bust 5
    RUN touch /root/hello-world.txt
    # https://github.com/PowerShell/PowerShell/issues/9252#issuecomment-486954264
    RUN apt-get update && apt-get install -y snapd selinux-utils selinux-policy-default rsync socat vim
    RUN echo "SELINUX=disabled" > /etc/selinux/config

  docker_bake_script: |-
    # Do things that cache docker images for faster builds,
    # like building a prior version of your software.
    # Buildkit cache is preserved!
    #!/bin/bash
    set -euo pipefail
    docker pull busybox:1.32.0

  preload_docker_images:
    # You can also pull docker images like this. Always use
    # immutable tags for reproducibility!
    - nginx:1.19.5
    - jujusolutions/juju-db:4.0
    - jujusolutions/jujud-operator:2.9-rc3
    # Get these from `ag upstream-source |cut -d ':' -f 4-` in bundle-kubeflow
    - gcr.io/kubeflow-images-public/katib/v1alpha3/katib-ui:v0.9.0
    - gcr.io/kubeflow-images-public/metadata-frontend:v0.1.8
    - gcr.io/tfx-oss-public/ml_metadata_store_server:v0.21.1
    - gcr.io/kubeflow-images-public/notebook-controller:v20191007-v0.6.0-rc.0-134-g6ddf28cc-dirty-560d95
    - gcr.io/kubeflow-images-public/katib/v1alpha3/katib-db-manager:v0.9.0
    - rocks.canonical.com:5000/kubeflow/katib-controller:latest
    - gcr.io/ml-pipeline/frontend:0.2.5
    - docker.io/seldonio/seldon-core-operator:1.2.1
    - gcr.io/ml-pipeline/viewer-crd-controller:0.2.5
    - gcr.io/ml-pipeline/persistenceagent:0.2.5
    - gcr.io/ml-pipeline/scheduledworkflow:0.2.5
    - gcr.io/ml-pipeline/visualization-server:0.2.5
    - gcr.io/kubeflow-images-public/profile-controller:v1.1.0-ga49f658f
    - gcr.io/kubeflow-images-public/kfam:v1.1.0-g9f3bfd00
    - gcr.io/kubeflow-images-public/pytorch-operator:v1.1.0-gd596e904
    - gcr.io/kubeflow-images-public/jupyter-web-app:9419d4d
    - gcr.io/kubeflow-images-public/tf_operator:v1.1.0-g92389064
    - argoproj/argoui:v2.3.0
    - argoproj/workflow-controller:v2.3.0
    - gcr.io/ml-pipeline/envoy:metadata-grpc
    - gcr.io/kubeflow-images-public/metadata:v0.1.11
    - minio/minio:RELEASE.2018-02-09T22-40-05Z
    - gcr.io/kubeflow-images-public/centraldashboard:v1.1.0-g35d7484a
    - gcr.io/ml-pipeline/api-server:0.2.5
    - metacontroller/metacontroller:v0.3.0
    - quay.io/dexidp/dex:v2.22.0
    - gcr.io/arrikto/kubeflow/oidc-authservice:fef11c3

  prewarm_script: |-
    # This gets run after each individual VM starts up, so
    # start services you need in your tests here and they'll be
    # already running when you testctl get
    #!/bin/bash
    set -xeuo pipefail
    # snappity snaps
    export PATH="/snap/bin:$PATH"
    # juju uses the hostname in the kubeconfig to try and connect _from_ the
    # pod to the apiserver. so give it an ip address that resolves to the host
    # from inside the pods.
    cd /root
    snap install juju --classic --channel=2.9/edge
    # Set kubeconfig to point to k8s apiserver on an address that's routable
    # from inside the pods, so jujud can access it.  In this case the docker
    # bridge.
    sed -i 's/localhost/172.17.0.1/' .kube/config

    echo "Running juju add-k8s"
    juju add-k8s --client testfaster
    echo "Running juju bootstrap"
    juju bootstrap --agent-version=2.9-rc4 testfaster

    # default service account has registry credentials, but juju needs them too
    # (testfaster created the secret regcred already.)
    kubectl patch serviceaccount -n controller-testfaster default -p '{"imagePullSecrets": [{"name": "regcred"}]}'

    juju add-model kf
    # cs: means "charm store", which is the "old place".
    # ch: means "charm hub", which is the "new place".
    juju deploy cs:bundle/kubeflow-255
    # wait for the role we need to patch to get created
    roles=0
    while [ "$roles" -eq "0" ] ; do
        roles=$(set +o pipefail; kubectl get roles --all-namespaces --no-headers |grep 'istio-ingressgateway-operator' |wc -l)
        echo $roles roles matching istio-ingressgateway-operator
        sleep 1
    done
    # from https://charmed-kubeflow.io/docs/install
    kubectl patch role -n kf istio-ingressgateway-operator -p '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"name":"istio-ingressgateway-operator"},"rules":[{"apiGroups":["*"],"resources":["*"],"verbs":["*"]}]}'
    # TODO: wait for kubeflow to be fully up

  # Need kube 1.17 for kubeflow last time I checked (1.18 doesn't work).
  # https://github.com/kubeflow/kubeflow/issues/5246#issuecomment-682013220
  kubernetes_version: v1.17.11

runtime:
  cpus: 4
  memory: 16GB
  disk: 50GB

# How many ready VMs to keep running for instant testctl get
prewarm_pool_size: 3

# Upper bound for pool size, e.g. to keep memory usage sensible
max_pool_size: 5

# Timeout VMs after this long. Set to "" if you want to use
# the VMs for long running development purposes rather than
# short-lived CI.
default_lease_timeout: ""

pool_sleep_timeout: "2d"
