name: Charmed kubeflow + mlflow bundle
base:
  kernel_image: quay.io/testfaster/ignite-kernel
  os_dockerfile: |-
    # This dockerfile defines the base disk image for your VMs
    FROM quay.io/testfaster/kube-ubuntu
    ENV cache-bust 5
    RUN touch /root/hello-world.txt
    # https://github.com/PowerShell/PowerShell/issues/9252#issuecomment-486954264
    RUN apt-get install -y snapd selinux-utils selinux-policy-default rsync
    RUN echo "SELINUX=disabled" > /etc/selinux/config

  docker_bake_script: |-
    # Do things that cache docker images for faster builds,
    # like building a prior version of your software.
    # Buildkit cache is preserved!
    #!/bin/bash
    set -euo pipefail
    docker pull busybox:1.32.0

  preload_docker_images:
    # You can also pull docker images like this. Always use
    # immutable tags for reproducibility!
    - nginx:1.19.5

  prewarm_script: |-
    # This gets run after each individual VM starts up, so
    # start services you need in your tests here and they'll be
    # already running when you testctl get
    #!/bin/bash
    set -xeuo pipefail
    # snappity snaps
    export PATH="/snap/bin:$PATH"
    # juju uses the hostname in the kubeconfig to try and connect _from_ the
    # pod to the apiserver. so give it an ip address that resolves to the host
    # from inside the pods.
    cd /root
    snap install juju --classic --channel=latest/edge
    # Set kubeconfig to point to k8s apiserver on an address that's routable
    # from inside the pods, so jujud can access it.  In this case the docker
    # bridge.
    sed -i 's/localhost/172.17.0.1/' .kube/config
    juju add-k8s --client testfaster
    juju bootstrap testfaster
    juju add-model kf
    # cs: means "charm store", which is the "old place".
    # ch: means "charm hub", which is the "new place".
    juju deploy cs:kubeflow
    # wait for the role we need to patch to get created
    roles=0
    while [ "$roles" -eq "0" ] ; do
        roles=$(set +o pipefail; kubectl get roles --all-namespaces --no-headers |grep 'istio-ingressgateway-operator' |wc -l)
        echo $roles roles matching istio-ingressgateway-operator
        sleep 1
    done
    # from https://charmed-kubeflow.io/docs/install
    kubectl patch role -n kf istio-ingressgateway-operator -p '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"name":"istio-ingressgateway-operator"},"rules":[{"apiGroups":["*"],"resources":["*"],"verbs":["*"]}]}'
    # TODO: wait for kubeflow to be fully up

  # Need kube 1.17 for kubeflow last time I checked (1.18 doesn't work).
  # https://github.com/kubeflow/kubeflow/issues/5246#issuecomment-682013220
  kubernetes_version: v1.17.11

runtime:
  cpus: 4
  memory: 16GB
  disk: 50GB

# How many ready VMs to keep running for instant testctl get
prewarm_pool_size: 3

# Upper bound for pool size, e.g. to keep memory usage sensible
max_pool_size: 5

# Timeout VMs after this long. Set to "" if you want to use
# the VMs for long running development purposes rather than
# short-lived CI.
default_lease_timeout: ""
