# Copyright 2020 Luke Marsden
# See LICENSE file for licensing details.
#
options:
  mlflow_port:
    description: |
      The port MLFlow will be listening on
    type: int
    default: 5000
  mlflow_nodeport:
    description: |
      The nodeport for MLFlow
    type: int
    default: 31380
  minio_port:
    description: |
      The port Minio will be listening on
    type: int
    default: 9000
  minio_nodeport:
    description: |
      The nodeport for Minio
    type: int
    default: 30650
  kubeflow_port:
    description: |
      The port Kubeflow will be listening on
    type: int
    default: 8082
  kubeflow_nodeport:
    description: |
      The nodeport for Kubeflow
    type: int
    default: 30600
